sudo: false
dist: trusty

language: go
go: "1.10"
cache:
  yarn: true
  apt: true
  directories:
    - $GOPATH/src/github.com/smartcontractkit/chainlink/vendor
    - $GOPATH/bin

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
        key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn

env:
  global:
    - DEP_VERSION="0.5.0"

before_install:
  # Go dependency manager dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Code climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $GOPATH/bin/cc-test-reporter
  - chmod +x $GOPATH/bin/cc-test-reporter

jobs:
  include:
    - stage: Test
      name: "Go Tests"
      script:
        - dep ensure
        - ./internal/ci/go_test
    - name: "Truffle Tests"
      script:
        - yarn install
        - ./internal/ci/truffle_test
    - name: "Ethereum Tests"
      script:
        - dep ensure
        - ./internal/ci/ethereum_test
    - name: "GUI Tests"
      script:
        - yarn install
        - ./internal/ci/gui_test
